name: elk

services:

  elasticsearch:
    image: elasticsearch:8.14.3
    networks:
      - elknet
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./conf/elasticsearch/conf.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx1G"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "sampleELK"
      discovery.type: single-node

  logstash:
    image: logstash:8.14.3
    depends_on:
      - elasticsearch
    networks:
      - elknet
    ports:
      - 5044:5044
      - 5010:5000
      - 9600:9600
    volumes:
      - ./conf/logstash/conf.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./conf/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./conf/logstash/pipelines:/usr/share/logstash/config/pipelines:ro
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"

  kibana:
    image: kibana:8.14.3
    depends_on:
      - elasticsearch
    networks:
      - elknet
    ports:
      - 5601:5601
    volumes:
      - ./conf/kibana/conf.yml:/usr/share/kibana/config/kibana.yml:ro

  nginx:
    image: nginx:latest
    networks:
      - elknet
    ports:
      - 8080:80
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./var/log/nginx:/var/log/nginx

  beats:
    image: elastic/filebeat:8.14.3
    command: filebeat -e -strict.perms=false
    depends_on:
      - nginx
      - elasticsearch
    networks:
      - elknet
    volumes:
      - ./conf/filebeat/conf.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./var/log/nginx:/var/log/nginx

networks:
  elknet:
    driver: bridge